name: FloorSync 2D
slug: floorsync_2d
version: "1.0.0"
description: FloorSync 2D Control Panel

arch:
  - amd64
  - armv7
  - armhf
  - aarch64

startup: application
boot: auto

ingress: true
ingress_port: 1337
panel_icon: mdi:floor-plan
panel_title: FloorSync 2D

host_network: false
init: false

options: {}
schema: {}

ports: {}